[package]
name = "device-api-tests"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
path = "lib.rs"

[dev-dependencies]
env = { path = "../../../crates/env" }
wire = { path = "../../../crates/wire" }
system-api = { path = "../../src/system/api" }
hub-api = { path = "../../src/service/hub/api" }
terminal-api = { path = "../../src/user/terminal/api" }
router-api = { path = "../../src/driver/router/api" }
