[package]
name = "runtime"
version.workspace = true
edition.workspace = true

# 镜像侧运行时：资源操作、任务本地原语与内存管理。
[lib]
path = "src/lib.rs"
test = false
bench = false
doctest = false

[dependencies]
env = { path = "../env" }
erra = { version = "0.2.0", default-features = false }
talc = { version = "=5.1.1", default-features = false }
spinning_top = { version = "=0.3.0", default-features = false }
