[package]
name = "hub-api-tests"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
path = "lib.rs"

[dev-dependencies]
env = { path = "../../../crates/env" }
hub-api = { path = "../../src/service/hub/api" }
system-api = { path = "../../src/system/api" }
wire = { path = "../../../crates/wire" }
