[package]
name = "terminal-client"
version.workspace = true
edition.workspace = true

[lib]
test = false
bench = false
doctest = false

[dependencies]
terminal-api = { path = "../api" }
env = { path = "../../../../../crates/env" }
wire = { path = "../../../../../crates/wire" }
resource = { path = "../../../../../crates/resource" }
ipc = { path = "../../../../../crates/ipc" }
system-client = { path = "../../../../../crates/system-client" }
system-api = { path = "../../../system/api" }
