(define (run plan)
  (let ((job (prepare plan)))
    (begin (foreground job) (start job) (wait job))))
(define (spawn plan)
  (let ((job (prepare plan)))
    (begin (background job) (start job) job)))
(define (fg job)
  (begin (foreground job) (resume job) (wait job)))
(define (bg job)
  (begin (background job) (resume job) job))
