[package]
name = "kernel"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags = "2.13.1"
erra = { version = "0.2.0", default-features = false }
fack = { version = "0.1.2", default-features = false }
fdt = { version = "0.1.5", default-features = false }
hashbrown = { version = "0.17.1", default-features = false, features = ["alloc", "default-hasher"] }
log = { version = "0.4.33" }
riscv = { version = "0.16.1", features = ["s-mode"] }
riscv-rt = { version = "0.18.0", features = ["s-mode"] }
riscv-semihosting = "0.2.1"


[[bin]]
name = "sqware"
path = "src/main.rs"
test = false
bench = false
doctest = false
