[package]
name = "loader-compat-tests"
version = "0.1.0"
edition = "2024"
publish = false
[workspace]
[dependencies]
env = { path = "../../../../../env" }
wire = { path = "../../../../../wire" }
system-api = { path = "../../../../../../programs/src/system/api" }
mold = { path = "../../../../../mold" }
[lib]
path = "lib.rs"
